// <auto-generated />
using FBC.Devices.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBC.Devices.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321154003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FBC.Devices.API.Models.AddrType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddrTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AddrTypes");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<bool>("IsSysAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SysUsers", (string)null);
                });

            modelBuilder.Entity("FBC.Devices.API.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("DeviceId");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceGroupId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.DeviceAddr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("DeviceAddrId");

                    b.Property<string>("Addr")
                        .HasColumnType("TEXT");

                    b.Property<int>("AddrTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PeriodicPingCheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddrTypeId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceAddresses");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.DeviceGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("DeviceGroupId");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceGroups");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.DeviceSearchData", b =>
                {
                    b.Property<int>("DeviceSearchDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceAddrId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceAddrTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("FieldTable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceSearchDataId");

                    b.HasIndex(new[] { "FieldTable", "DeviceId", "FieldName" }, "IDX_DeviceSearchData_Freq_Fields");

                    b.HasIndex(new[] { "DeviceId" }, "IX_DeviceSearchData_DeviceId");

                    b.HasIndex(new[] { "FieldTable", "DeviceId", "DeviceTypeId", "DeviceGroupId", "DeviceAddrId", "DeviceAddrTypeId", "FieldName" }, "UX_DeviceSearchData_Key")
                        .IsUnique();

                    b.ToTable("DeviceSearchMetas");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("DeviceTypeId");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.Device", b =>
                {
                    b.HasOne("FBC.Devices.API.Models.DeviceGroup", "DeviceGroup")
                        .WithMany()
                        .HasForeignKey("DeviceGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FBC.Devices.API.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeviceGroup");

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.DeviceAddr", b =>
                {
                    b.HasOne("FBC.Devices.API.Models.AddrType", "AddrType")
                        .WithMany()
                        .HasForeignKey("AddrTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FBC.Devices.API.Models.Device", null)
                        .WithMany("DeviceAddresses")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddrType");
                });

            modelBuilder.Entity("FBC.Devices.API.Models.Device", b =>
                {
                    b.Navigation("DeviceAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
